### ISSUE TITLE
Code design review

### ISSUE THREAD

**Issue by Naddybs** [SamaraFellaDina/the-web-is-for-everyone-interactive-functionality#1]
Hier zijn suggesties om de HTML code te verbeteren met betrekking tot semantiek en structuur:

1. Verwijder de onnodige div rond de section met elementen. Aangezien je al een ul hebt met li elementen, is deze extra wrapper niet nodig en draagt deze niet bij aan de semantiek van de HTML.

2. Overweeg om het section element op regel 4 te vervangen door een article element om je semantiek waardevol te maken.

3. Voeg het time element toe op regel 21 om de tijdsemantiek beter te markeren, waardoor het duidelijker wordt voor browsers wat voor inhoud je wil weergeven.

4. Je kan de elementen van regel 28 tot 39 binnen een ul plaatsen van meerdere section elementen onder elkaar. Hierdoor wordt de structuur van de lijsten duidelijker en beter gestructureerd.

- Je button state nadat je een actie hebt uitgevoerd geeft "link gekopieerd" weer, hierdoor zie je de oorspronkelijke boodschap niet meer. Denk aan mogelijke oplossingen.
- Goed dat je de button duidelijk hebt weergegeven met een felle kleur, het is de bedoeling dat de button aantrekkelijk genoeg is voor gebruikers om actie te nemen.

Je design overall ziet er heel goed uit! Je houd je goed aan de huisstijl en de gegeven user story.

**Comment by SamaraFellaDina** [comment]
Zorg dat je schetsen voor de User story goed weergeeft hoe vaak het is gedeeld.
